# Generated by Django 5.0 on 2023-12-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskslist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskslist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskslist',
            name='title',
        ),
        migrations.AddField(
            model_name='taskslist',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks_list', to='tasks.task'),
        ),
    ]
