# Generated by Django 5.0 on 2023-12-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_remove_taskslist_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskslist',
            old_name='user',
            new_name='username',
        ),
    ]
