# Generated by Django 5.0 on 2023-12-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_user_taskslist_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskslist',
            old_name='username',
            new_name='user',
        ),
    ]
